services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./html:/html  # Mount html folder to /html
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./logs:/app/logs
    expose:
      - "8000"
    depends_on:
      - main
    restart: unless-stopped
    networks:
      - bot_network

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - main
      - api
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge